/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Exercicio01 ex = new Exercicio01();
        // int resp = ex.solve(1, 1);
        System.out.println(ex);
    }
}
