/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testExercicio01HasSolve() {
        Exercicio01 classUnderTest = new Exercicio01();
        assertNotNull("Classe Exercicio01 deveria ter método solve()", classUnderTest.solve(1,1));
    }

    @Test
    public void testExercicio01Solve() {
        Exercicio01 classUnderTest = new Exercicio01();
        int res = classUnderTest.solve(1,1);
        assertEquals(2, res);
        res = classUnderTest.solve(10,9);
        assertEquals(19, res);
        res = classUnderTest.solve(-10,4);
        assertEquals(6, res);
        res = classUnderTest.solve(10,-10);
        assertEquals(0, res);
    }

    @Test
    public void testExercicio02HasSolve() {
        Exercicio02 exercicio = new Exercicio02();
        assertNotNull("Classe Exercicio02 deveria ter método solve()", exercicio.solve(1,1));
    }

    @Test
    public void testExercicio02Solve() {
        Exercicio02 exercicio = new Exercicio02();
        int res = exercicio.solve(5.0, 7.1);
        assertEquals("O resultado deveria ser 6.43182", 6.43182, res, 0.001);
        res = exercicio.solve(0.0, 7.1);
        assertEquals("O resultado deveria ser 4.84091", 4.84091, res, 0.001);
    }
}
